[package]
name = "MongoToolsCLI"
version = "0.2.0"
edition = "2021"

[dependencies]
mongodb = "3.2.5"
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tar = "0.4.4"
flate2 = "1.1.9"
chrono = "0.4.45"
futures = "0.3.33"
colored = "3.1.1"
cron = "0.17.0"
serde = { version = "1.0.229", features = ["derive"] }
url = "2.5.8"